### PR TITLE
add signup page

### PR DESCRIPTION
**Pull request by Ryadav0654**
fixes:  #85

- Created a new Signup component with a form for user registration.
- Styled the form using Material-UI  and tailwind css

#### Screenshot
https://github.com/user-attachments/assets/1887b2f0-ae88-40d7-bca5-9e0951c2fa92

### CODE REVIEW

**Comment by Ryadav0654** [comment]
Hi @Vin-Jex,

I’ve created this pull request with the following updates:
- Added a signup page with responsiveness and support for both dark and light themes.

If anything needs to be changed or improved on the signup page, please let me know. I’m happy to make adjustments based on your feedback!
Could you please review the changes when you have time? Your feedback would be greatly appreciated!

Thanks!

**Comment by Vin-Jex** [comment]
> Hi @Vin-Jex,
> 
> I’ve created this pull request with the following updates:
> 
> * Added a signup page with responsiveness and support for both dark and light themes.
> 
> If anything needs to be changed or improved on the signup page, please let me know. I’m happy to make adjustments based on your feedback! Could you please review the changes when you have time? Your feedback would be greatly appreciated!
> 
> Thanks!

Here’s a rephrased and more structured version that communicates the feedback clearly and professionally:

---

**Hi @Ryadav0654 **

Thank you for your contribution! I’ve reviewed your pull request, and I appreciate the work you’ve done so far. Here’s some feedback on the signup page:

1. **Keep Your Branch Updated**  
   Before proceeding, please ensure that your branch is up-to-date with the `main` branch.

2. **Signup Page Feedback**  
   - **Left Content Layout**: The content on the left should fill the entire width and height. Currently, there’s space around the layout, which shouldn’t be the case. Ensure both the left and right sections are fully stretched to the edges.
   - **Left Navigation**: Don’t worry about the left navigation for now. Just place a `div` with a background color that fills the entire width of the left section.
   - **Right Content Responsiveness**: The right content needs to be fully responsive. When the screen size reduces, the two columns in the first row of the form should stack into two rows with one column each.

3. **Dark Mode Background**  
   When toggling to dark mode, the background color should be `#212423`. If you need any specific tools or information, feel free to ask, and I’ll provide you with what’s needed.

Let me know if you have any questions or need further clarification. I’m happy to assist!
---

**Comment by Vin-Jex** [comment]
@Ryadav0654 

Please resolve this issue quick else I would close this PR and make the issue opened for grab again.

IMG_2886

**Comment by Vin-Jex** [comment]
Firsly, you failed to fix the bug I raised previously and lastly, this branch now has a merge conflict. So resolve the bug, update you branch and fix merge conflict. Thank you!

**Pull request closed without merging**
