### PR TITLE
fix hero section images

### PR DESCRIPTION
**Pull request by bulutyerli**
Screenshot 2024-10-01 at 19 46 34

### Summary of Changes:

- Updated Images: Replaced the hero section images based on the new design.
- New Images Added: Added 3 new images due to the original images being too small for the design requirements.
- Image Directory: Created a new folder named hero-images inside the public/images directory to store the updated images. The images are sourced from Unsplash and kept same file names as the originals for easy change
- Code Change: Made changes on the hero and heroMap components and implemented design with tailwind.

**Issue Addressed:**
This update addresses issue #78.

### CODE REVIEW

**Comment by Vin-Jex** [comment]
> Screenshot 2024-10-01 at 19 46 34
> 
> ### Summary of Changes:
> * Updated Images: Replaced the hero section images based on the new design.
> * New Images Added: Added 3 new images due to the original images being too small for the design requirements.
> * Image Directory: Created a new folder named hero-images inside the public/images directory to store the updated images. The images are sourced from Unsplash and kept same file names as the originals for easy change
> * Code Change: Made changes on the hero and heroMap components and implemented design with tailwind.
> 
> **Issue Addressed:** This update addresses issue #78.

Yes, you've made some update but you're yet to completely resolve that issue.

Compare the UI and your new update you would realise the right content is too small hence resulting in lot of space at the right side of the screen the left content too is too small.

- **Hints**
   - Make the container to have a width of full and position it to the center.
   - Add a flexbox and justify between for the two content (right and left)
   - the left content should fill 45% of it width and same for right.

**Comment by bulutyerli** [comment]
@Vin-Jex I have just committed new fixes, can you check.

**Comment by Vin-Jex** [comment]
> @Vin-Jex I have just committed new fixes, can you check.

@bulutyerli Well done!

- **Issues Yet to be fixed**
   - Images are still small on desktop devices
   - Left content responsiveness is very bad, the text are too big on mobile and tablets screens - it didn't change as the screen size reduces.
   
- **Bonus**
   - Images border-radius should be reduced as the screen size become small.

**Comment by bulutyerli** [comment]
@Vin-Jex

I've made additional changes, including fixes for the responsiveness of the left section.

However, there are still some issues with the responsiveness of the header section. I recommend creating a new issue to address the overall responsiveness of the website.

**Review by Vin-Jex — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
